### ISSUE TITLE
How do I get replies from multiple processes?

### ISSUE THREAD

**Issue by kleinschmidt-1511** [mehmetozturk4705/async_message_handler#1]
Hello, 

i try to use your lib for more than one process. But only one process replies. 

This is my code so far:

`import time
import asyncio
import multiprocessing as mp

from asynchronous_message_handler import ProcessCommandHandler, CommandContext, ProcessCommand, Events

handler = ProcessCommandHandler(timeout=15)

def sample_process(context: CommandContext, i):
    print(i)
    context.initialize()
    print(context._get_context_id())

    command: ProcessCommand = context.get_next(block=True)
    print(command.get_payload())
    time.sleep(5)
    command.reply("Hello from process.")
    while True:

        time.sleep(5)
        context.send_message("This is a late message from process.")

@handler.on(Events.NewMessage)
def message_callback(message):
    print(message)

async def main():
    response = await handler.command("Hello from asyncio.")
    print(response)
    await asyncio.sleep(8)

if __name__ == "__main__":
    for i in range(5):
        process = mp.Process(target=sample_process, args=(
            handler.get_command_context(), i,))
        print(handler.get_command_context())
        process.start()
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    process.join()
`

**Comment by mehmetozturk4705** [comment]
Hello,
Thanks for using the async-message-handler. You can use multiple processes as below.

    import time
    import asyncio
    import multiprocessing as mp
    from asynchronous_message_handler import ProcessCommandHandler, CommandContext, ProcessCommand, Events
    
    #Creating new command handler object.
    handler = ProcessCommandHandler(timeout=15)
    
    
    def sample_process1(context:CommandContext):
        #You should initialize context to be bound.
        context.initialize()
    
        #Waits until new message, this operation is blocking for this process.
        #If you want it to be nonblocking use blocking=False parameter.
    
        command:ProcessCommand = context.get_next()
        print(command.get_payload())
    
        #Sleep for 5 seconds.
        time.sleep(5)
        command.reply("Hello from process 1.")
    
        time.sleep(5)
        #Send message from process to asynchronous context.
        context.send_message("This is a late message from process 1.")
    
    def sample_process2(context:CommandContext):
        #You should initialize context to be bound.
        context.initialize()
    
        #Waits until new message, this operation is blocking for this process.
        #If you want it to be nonblocking use blocking=False parameter.
    
        command:ProcessCommand = context.get_next()
        print(command.get_payload())
    
        #Sleep for 5 seconds.
        time.sleep(5)
        command.reply("Hello from process 2.")
    
        time.sleep(5)
        #Send message from process to asynchronous context.
        context.send_message("This is a late message from process 2.")
    
    
    #This is a sample event handler for new messages from process/thread.
    @handler.on(Events.NewMessage)
    def message_callback(message):
        print(message)
    
    
    async def main():
        #This is asyncio context.
        response1 = asyncio.get_running_loop().create_task(handler.command("Hello from asyncio."))
        response2 = asyncio.get_running_loop().create_task(handler.command("Hello from asyncio."))
        print(await response1)
        print(await response2)
        #Waiting for a while for sample process to loop message demo.
        await asyncio.sleep(8)
    
    
    
    if __name__=="__main__":
        process1 = mp.Process(target=sample_process1, args=(handler.get_command_context(),))
        process2 = mp.Process(target=sample_process2, args=(handler.get_command_context(),))
        process1.start()
        process2.start()
        loop = asyncio.get_event_loop()
        loop.run_until_complete(main())
        process1.join()
        process2.join()

As you can see above you need to initialize the handler in every single process/thread. 
The first available process will get the message from the context queue. If you would like to use different process/thread groups as workers, you shall create different handlers per group.

**Comment by kleinschmidt-1511** [comment]
Hello,
thank you for your very quick reply.
